### ISSUE TITLE
If the resource name contains a "-" no bust parameter is appended

### ISSUE THREAD

**Issue by sorenmalling** [Flowpack/Flowpack.CacheBuster#1]
If the resource linked to, for example `Images/Modules/contact-informations.png` contains a dash ('-') then there is not added a cachebust

For example

```
Images/Modules/invoices.png?bust=b7c40608
Images/Modules/payment-information.png
```

**Comment by Sebobo** [comment]
I can't reproduce this at least with a css file:

<img width="640" alt="bildschirmfoto 2017-12-19 um 14 03 25" src="https://user-images.githubusercontent.com/596967/34144742-7c0e8e62-e4c5-11e7-8e2c-37341cbd0789.png">

How do you reference the image?

**Comment by sorenmalling** [comment]
@Sebobo I make the reference like this

`<img src="../../../Public/Images/gold-logo.png" id="logo"/>`

and then `ResourceInterceptor` picks it up and creates the url

**Comment by cwenzelg** [comment]
i got into the same problem right now. i got a svg that loads without the ?bust part, but not with. but it has no "-" only "_" and it is a .svg icon. No idea why. the other resources load just fine.

**Comment by Sebobo** [comment]
Hi @sorenmalling it's possible this doesn't trigger the `getPublicPackageResourceUri`. If you use the fluid viewhelper instead it should work:

    {f:uri.resource(path: 'resource://DifferentPackage/Public/gfx/SomeImage.png')}

**Comment by kdambekalns** [comment]
@Sebobo The interceptor builds `ResourceViewHelper` nodes, and those use `getPublicPackageResourceUri`, see https://github.com/neos/flow-development-collection/blob/a243279289773552113c6ea44566054dc93bd546/Neos.FluidAdaptor/Classes/ViewHelpers/Uri/ResourceViewHelper.php#L154

**Comment by kdambekalns** [comment]
It seems to be an issue with the regex in the resource interceptor… not caused by the cache buster.
